import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Header } from './header'
import { about } from './about'
import Layout from './layout'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Sobar Bazar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <h2 style={{textAlign:'center',marginTop:'20px'}}>Welcome <span style={{color:'green'}}>Next.js</span></h2>

      <p className={styles.card}>Learn about Next.js in an interactive course with quizzes!</p>

      </div>

      
    </div>
  )
}

Home.getLayout = function getLayout(page) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}
